[versions]
agp = "8.13.1"
kotlin = "2.2.21"
activity = "1.12.1"
appcompat = "1.7.1"
constraintlayout = "2.2.1"
material = "1.13.0"
fragment-ktx = "1.8.9"

[libraries]
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
fragmentktx = { group = "androidx.fragment", name= "fragment-ktx", version.ref = "fragment-ktx" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
